aptos tutorial
pontem-network/docs pull request #26
Opened 2022-05-25 19:04 UTC by mkurnikov

2022-06-03 01:08 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +it has a lot of restrictions which prevent developers from shooting themselves in a foot and miss
let's replace restrictions with improvements?

2022-06-03 01:17 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +TODO: expand on Aptos
Asked Alejo to helo here

2022-06-03 14:11 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +Aptos is focused on delivering the safest, fastest and most reliable production-ready Layer 1 blockchain to create creating universal and fair access to web3 for billions of people. Aptos recently an
Let's make it's some kind of quote

2022-06-03 14:23 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +First, create a directory and initialize it with a Package using aptos-cli:
using aptos binary?

2022-06-03 16:18 UTC, borispovod requested changes

2022-06-03 16:18 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +which allow to communicate with said storage from the Move code.
Maybe let's mention that arguments for that functions usually addresses, but to store something dev needs signer?

2022-06-03 16:18 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +    public fun get_username(account: &signer): String acquires InfoStore {
why we need signer here? if i want to look at someone else username?

2022-06-03 16:18 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +    public fun set_username(account: &signer, username: String) acquires InfoStore {
in the next part we should make it script

2022-06-03 16:18 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +module Sender::UserInfoTests {
You forgot #[test_only] before module :)

2022-06-03 16:18 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +Now, to run this test:
Would be good to continue with:

* Convert public function to script
* Publish modules
* Run scripts

I can help with it if needed

2022-06-06 08:07 UTC, borispovod commented on tutorials/aptos-tutorial.md
> +[https://github.com/aptos-labs/aptos-core/releases], and download zip archive for your OS.
broken link

2022-06-06 17:35 UTC, mkurnikov commented on tutorials/aptos-tutorial.md
> +Let's add an address with name `Sender` and value `0x42` under the `[addresses]`. We're going to store all our modules at that
That's just an arbitrary value

2022-06-09 11:09 UTC, mkurnikov commented on tutorials/aptos-tutorial.md
> +The deployment config which contains the private key of the new account would be created in `.aptos/config.yaml`. Don't share your private key with anyone! If you want to change configuration or acco
`.aptos/config.yaml` in the root of the project?

2022-06-10 18:54 UTC, merged